---
version: "3.8"

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
     - "127.0.0.1:5432:5432"

    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -d $POSTGRES_DB -U $POSTGRES_USER"
      interval: 3s
      timeout: 5s
      retries: 5

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
